name: pgc_lunarreg
channels:
  - conda-forge
dependencies:
  - configargparse
  - gdal
  - geopandas
  - lxml
  - numpy
  - opencv
  - pandas
  - pathlib2
  - pip
  - postgresql
  - psycopg2
  - pytest
  - python
  - python-dateutil
  - rasterio
  - rtree
  - scipy
  - shapely
  - sqlalchemy
  - tqdm